---
# Handler to handle DB tier notifications

- name: restart mysql
  service:
    name: mysqld
    state: restarted

- name: restart mariadb
  service:
    name: mariadb
    state: restarted

- name: restart iptables
  service:
    name: iptables
    state: restarted
