---
# This playbook contains common plays that will be run on all nodes.

- name: Install ntp
  yum:
    name: ntp
    state: present
  tags: ntp

- name: Configure ntp file
  template:
    src: ntp.conf.j2
    dest: /etc/ntp.conf
  tags: ntp
  notify: restart ntp

- name: Start the ntp service
  service:
    name: ntpd
    state: started
    enabled: yes
  tags: ntp

- name: test to see if selinux is running
  command: getenforce
  register: sestatus
  changed_when: false
- name: Change Ulimits
  pam_limits:
    domain: centos
    limit_type: soft
    limit_item: nofile
    value: 64000
- name: debug 
  debug: 
    msg: "We have completed the common configuration for all servers"
