---
- hosts: all
  gather_facts: no
  vars:
    custom_variable: "default_value"

  tasks:
  - name: Manually gather facts
    setup:
      filter: ["ansible_fqdn"]

  - name: Prints various Ansible facts
    debug:
      msg: >
        The default IPv4 address of {{ ansible_fqdn }} 
        is {{ ansible_default_ipv4.address }}

