---
- name: Check if a number is even
  hosts: group2
  vars:
    install_list: ['httpd', 'tree', 'mariadb']
    number: 46
    another_number: 5 
  tasks:
    - name: Check if number is even
      yum:
        name: "{{ item }}"
        state: present 
      loop:  
        "{{ install_list }}"
      when: another_number < 10
    - name: Use debug
      debug:
        msg: "{{another_number}}"
