---
- name: Check if a number is even
  hosts: all
  vars:
    number: 4
  tasks:
    - name: Check if number is even
      debug:
        msg: "The number {{ number }} is even."
      when: number % 2 == 0
