---
- name: Display all elements of a list
  hosts: localhost
  vars:
    sample_list: ['item1', 'item2', 'item3', 'item4']
  tasks:
    - name: Print each item
      debug:
        msg: "{{ item }}"
      loop: "{{ sample_list }}"
