name: Run Ansible Playbook

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible

    - name: Run Ansible playbook
      env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
         echo ${PRIVATE_KEY} > key_file.pem
         chmod 600 key_file.pem
         cp .env-template .env
         source .env
         echo $INVENTORY
         echo $PLAYBOOK
         echo $USER
         cat key_file.pem
         export PLAYBOOK=${PLAYBOOK} INVENTORY=${INVENTORY} USER=${USER} && ansible-playbook all-playbooks/${PLAYBOOK} -i all-playbooks/${INVENTORY} --user ${USER} --become --private-key key_file.pem

    - name: Print the result
      run: echo "Playbook run successfully!"
